// app/pages/color-palette.ts

export const ColorPalette = {
  Background: {
    bgLight: "#FFFFFF",
    bgDarken: "#F8F8F8",
  },
  Greyscale: {
    textPrimary: "#181818",
    textSecondary: "#5C5C5C",
    textTertiary: "#747474",
    icons: "#7C7B7B",
    stroke: "#D7D7D7",
    dividers: "#EDEDED",
    disabledText: "#8A8A8A",
    disabledBg: "#EFEFEF",
    white: "#FFFFFF",
    textOnColorPlashes: "#181818",
  },
  AccentViolet: {
    accent1Primary: "#2D5BFF",
    accent1Secondary: "#6284FD",
    accent1Tertiary: "#96ADFF",
    accent1Quaternary: "#ECF0FF",
    hoverState: "#1B4AF0",
    clickState: "#002ED0",
  },
  AccentOrange: {
    accent2Primary: "#FF7F37",
    accent2Secondary: "#FC9D68",
    accent2Tertiary: "#FFD5BE",
    accent2Quaternary: "#FFECE1",
  },
  SystemColors: {
    successfulHover: "#28B411",
    successful: "#28B411",
    successfulSecondary: "#B2FFA6",
    successfulTertiary: "#E6FFE2",
    attentionHover: "#F6D523",
    attention: "#F6D523",
    attentionSecondary: "#FFEF98",
    attentionTertiary: "#FFF2F2",
    errorHover: "#ED2121",
    error: "#FF3030",
    errorSecondary: "#FFC0C0",
    errorTertiary: "#FFF2F2",
  },
};

export const ColorPaletteDark = {
  Background: {
    bgLight: "#181818",
    bgDarken: "#121212",
  },
  Greyscale: {
    textPrimary: "#E0E0E0",
    textSecondary: "#B0B0B0",
    textTertiary: "#A0A0A0",
    icons: "#B8B8B8",
    stroke: "#4D4D4D",
    dividers: "#3A3A3A",
    disabledText: "#A0A0A0",
    disabledBg: "#2A2A2A",
    white: "#FFFFFF",
    textOnColorPlashes: "#E0E0E0",
  },
  AccentViolet: {
    accent1Primary: "#4A6BFF",
    accent1Secondary: "#7A9BFD",
    accent1Tertiary: "#B0C1FF",
    accent1Quaternary: "#E0E6FF",
    hoverState: "#2B4AF0",
    clickState: "#003ED0",
  },
  AccentOrange: {
    accent2Primary: "#F37B38",
    accent2Secondary: "#EA996B",
    accent2Tertiary: "#FFAB7C",
    accent2Quaternary: "#FFC2A0",
  },
  SystemColors: {
    successfulHover: "#4CAF50",
    successful: "#4CAF50",
    successfulSecondary: "#A5D6A7",
    successfulTertiary: "#C8E6C9",
    attentionHover: "#FBC02D",
    attention: "#FBC02D",
    attentionSecondary: "#FFEB3B",
    attentionTertiary: "#FFF9C4",
    errorHover: "#F44336",
    error: "#F44336",
    errorSecondary: "#FFCDD2",
    errorTertiary: "#FFEBEE",
  },
};
